### ISSUE TITLE
hackage-docs: All links in Algorithm section go to 404.

### ISSUE THREAD

**Issue by maralorn** [cdepillabout/password#17]
I guess the title is enough.

**Comment by cdepillabout** [comment]
It looks like this section:

https://github.com/cdepillabout/password/blob/5f46d4ae99ec80aa0ae665e08b622ac55c54192f/password/src/Data/Password.hs#L25-L37

I guess things like `@"Argon2"@` should be changed to `@"Data.Password.Argon2"@`.

We'd appreciate a PR fixing this.
