### ISSUE TITLE
support for cryptonite-0.27

### ISSUE THREAD

**Issue by cdepillabout** [cdepillabout/password#23]
Cryptonite has a new release that we should support:

http://hackage.haskell.org/package/cryptonite-0.27

This is from https://github.com/commercialhaskell/stackage/issues/5466.

My guess is that all this will require is bumping the cryptonite version and making a new release.

**Comment by Vlix** [comment]
I'll see if I can check to see if anything needs updating this weekend.

**Comment by Vlix** [comment]
Added revision on hackage for `password-2.0.1.1` and added the change in #24
