### ISSUE TITLE
Update documentation on password policy validation

### ISSUE THREAD

**Issue by agentultra** [cdepillabout/password#30]
There should be a link to well-cited research that complex password policies are _not_ recommended and should be used with caution:

https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-63b.pdf

See Appendex 1 of that paper

Recommend adding that link to the documentation of the validation module and checking that the default policy reflects the NIST recommended guidelines.

**Comment by agentultra** [comment]
Opened a draft PR for early feedback on the idea: #31

**Comment by Vlix** [comment]
Thanks for sharing the PDF and initiating the update.
#38 and #39 have added documentation to inform users about best practices and linking to the NIST PDF.

Closing this issue.
