### ISSUE TITLE
Support for [bcrypt]

### ISSUE THREAD

**Issue by Vlix** [cdepillabout/password#4]
Just found this library and it's not bad (surprised the `password` name wasn't used before), but would like to see more from this library for convenience.

`bcrypt` is still widely used and shouldn't be too difficult to add (we have an implementation of it very similar to this library)
Maybe a good idea to move functions specific to a certain encryption to their own modules so that it's easier to know what you're using. e.g.:

```haskell
import Data.Password (Pass)
import qualified Data.Password.Scrypt as Scrypt
import qualified Data.Password.Bcrypt as Bcrypt

myCheck :: Pass -> Either Scrypt.PassHash Bcrypt.PassHash -> PassCheck
myCheck pass = either (Scrypt.checkPass pass) (Bcrypt.checkPass pass)
```

**Comment by cdepillabout** [comment]
This sounds like a good idea.  I'd definitely accept a PR adding this.

Although I think it would probably just be easier to keep everything in `Data.Password` and just have `checkPassScrypt`, `checkPassBcrypt`, etc functions.

**Comment by cdepillabout** [comment]
Although now that I think about this, you'd also need corresponding hashing functions for both Scrypt and Bcrypt, so maybe adding them to different modules would be easier!

Although I do think that `Data.Password.Bcrypt` and `Data.Password.Scrypt` should re-export everything from `Data.Password` (which should really only contain the `Pass` and `PassHash` types, and related functions).  That way the end user generally won't have to import both `Data.Password` and `Data.Password.Bcrypt`.

**Comment by Vlix** [comment]
Yes, it'd be more user friendly to re-export the common data types too.

Might even be nice to also add `PBKDF2`, since then you'd have all 3 "generally" accepted standards of password hashing.

**Comment by cdepillabout** [comment]
> I'd opt for having the PassHash data type be changed to ScryptHash and BcryptHash

I was thinking that just having phantom types on `PassHash` would be fine.

So we could have `PassHash Scrypt` and `PassHash Bcrypt`.

If anyone wanted to write instances for `PassHash`, they'd generally just have to write them for `PassHash a` and have them apply to both `PassHash Scrypt` and `PassHash Bcrypt`.

> Might even be nice to also add PBKDF2, since then you'd have all 3 "generally" accepted standards of password hashing.

This definitely sounds like a good idea too!
