### ISSUE TITLE
How long is a `PasswordHash Bcrypt`? Could use documentation

### ISSUE THREAD

**Issue by sullyj3** [cdepillabout/password#59]
I'm not sure how large to make the CHAR(n) in my database. Googling, it seems like a bcrypt hash can be either 59 or 60 bytes depending on the specific algorithm used. Is this correct? Which does `password` use? It would be useful to have this info in the haddocks.

I'm happy to submit a PR updating the docs if I can get a list of the sizes for each of the supported algorithms

**Comment by Vlix** [comment]
I've done a small bit of research, and you are right. It is possible that the hash COULD be 59 characters, but that would mean it is a hash that uses the original `$2$` version of `bcrypt`, which was missing a few things in its specification. The "fixed" original version of `bcrypt` was then decided to be `$2a$`.

`$2x$` and `$2y$` are used in a PHP implementation which were created after a bug was found in that library, but not used outside of PHP, AFAICT

A bug was found in the OpenBSD implementation of `bcrypt` and they decided to bump the version after that fix to `$2b$` (in 2014), **which is what the Haskell implementation uses**, and I think pretty much any other up-to-date non-PHP implementation. (though the `$2y$` hashes ARE acceptable in the Haskell implementation, IIRC 🤔 )

So to answer your question, **a `bcrypt` hash is 60 characters long, and will probably stay that way indefinitely**.

---

If you'd like to add that fact to the documentation in a helpful way, you're free to make a PR 👍

**Comment by cdepillabout** [comment]
Thanks, the documentation here was clarified in #69
