### ISSUE TITLE
Support ByteString v0.11

### ISSUE THREAD

**Issue by prikhi** [cdepillabout/password#60]
`password` has dropped out of stackage nightly due to the following build error:

```
        - password < 0 # tried password-3.0.1.0, but its *library* requires bytestring >=0.10.8.1 && < 0.11 and the snapshot contains bytestring-0.11.3.1
```

Upper bounds needs to be bumped to `< 0.12`. Also noticed the test-suite was disabled due to a now fixed issue:

```
    - password # Module not visible https://github.com/cdepillabout/password/issues/2
```

**Comment by cdepillabout** [comment]
This has been fixed in https://github.com/cdepillabout/password/pull/58, and I added a revision for it on hackage: https://hackage.haskell.org/package/password-3.0.1.0/revisions/

**Comment by cdepillabout** [comment]
Re-added to stackage nightly in https://github.com/commercialhaskell/stackage/pull/6679.
