### ISSUE TITLE
Hackage notice: `bytestring-0.12.0.1`

### ISSUE THREAD

**Issue by Vlix** [cdepillabout/password#67]
The dependency bytestring-0.12.0.1 has been updated.

You have requested to be notified when a dependency isn't accepted by any of your maintained packages.

These are your packages that require `bytestring` but don't accept `0.12.0.1`:

`password-3.0.2.1`

**Comment by Vlix** [comment]
Set a PR #68

**Comment by cdepillabout** [comment]
Closed by #68, and the version on Hackage has an appropriate revision applied.
