### ISSUE TITLE
Adjust `password` to also build with `base64-1.0`

### ISSUE THREAD

**Issue by Vlix** [cdepillabout/password#73]
[`base64-1.0`](https://hackage.haskell.org/package/base64-1.0) has a new interface, the ChangeLog says, so it probably needs some code changes to be compatible.

I'd rather we build with `base64 < 1.0` and `>= 1.0`, so we might need to use some `CPP`.

**Comment by ysangkok** [comment]
Stackage issue for the record:

* https://github.com/commercialhaskell/stackage/issues/7279

**Comment by Vlix** [comment]
Issue fixed with version 3.0.4.0
