### ISSUE TITLE
RFC 8018 support

### ISSUE THREAD

**Issue by ysangkok** [cdepillabout/password#76]
It would be nice if the library supported the [ASN.1 structures in RFC 8018](https://www.rfc-editor.org/rfc/rfc8018.html#appendix-A.2). Using the standard, it would be possible to use the salt/keyLength/prf configuration in other languages with less conversion work. This would also make it easier to verify that the Haskell implementation is correct.

**Comment by Vlix** [comment]
You want _this_ library to support this?
Do you have a rough example (pseudo code is fine too) on what this would look like?

Verifying that the KDF implementation is correct would be part of the underlying crypto library (i.e. `crypton(ite)`), no? 🤔

**Comment by ysangkok** [comment]
@Vlix 

> You want this library to support this?

Yes, I think it would make sense, since the library is already focused on emitting password hashes that contain additional metadata like iteration count. As far as I understand, this format is called [PHC](https://github.com/P-H-C/phc-string-format/blob/master/phc-sf-spec.md), even though I don't see it mentioned in the documentation. I'd be curious to know how this format was chosen, and if it's not PHC, how come it looks so similar?

> Do you have a rough example (pseudo code is fine too) on what this would look like?

From a client perspective, I think usage would be the same. What RFC8018 offers is just an alternative to PHC. Instead of dollar signs, ASN.1 is more tightly packed, and not string based.

> Verifying that the KDF implementation is correct

I think this is out of scope since this is just about encoding metadata, not the KDF itself.

**Comment by Vlix** [comment]
I think I have a better idea what this is about now. Please correct me if I'm wrong:
- RFC8018 is a way to represent a password hash with its accompanying parts
- ASN.1 is a way to define encodeable/decodeable types
- You're suggesting to add a way to output hashes from `hashPassword` in an ASN.1 type (e.g. using [`asn-types` package](https://hackage.haskell.org/package/asn1-types)?), instead of a `Text`, so that users of the `password` package have more ways to en/decode the same "result" from hashing a password?

**Comment by ysangkok** [comment]
Yes. That is the gist of it. But I am having a hard time finding implementations that actually use ASN.1. So I wonder if those structures aren't actually used by anyone. If that's the case, then this proposal makes no sense.

For now, I suppose it would make sense to document whether the returned format conforms to the PHC specification. Do you know if that's the case?

**Comment by Vlix** [comment]
From what I've read from the specification, I think yes, the Argon2(id) hash conforms to it. This is kind of how the hashes were decided:
- `bcrypt`: has it's pre-defined hash format
- `PBKDF2`: copied from [12100 | PBKDF2-HMAC-SHA512](https://hashcat.net/wiki/doku.php?id=example_hashes)
- `scrypt`: backwards compatible from the [`scrypt` library](https://hackage.haskell.org/package/scrypt)
- `Argon2`: copied from other implementations (which are based on PHC IIRC)

**Comment by ysangkok** [comment]
Oh, I hadn't seen that. I'll close this then, thanks for the pointer!
