### ISSUE TITLE
`crypton` now at version `1.0.0`

### ISSUE THREAD

**Issue by Vlix** [cdepillabout/password#78]
Need to try and build `password` package with `crypton-1.0.0` and make a revision on hackage if everything still works.

**Comment by cdepillabout** [comment]
Looks like stackage is trying to drop cryptonite, so we should probably make this switch: https://github.com/commercialhaskell/stackage/issues/7474

**Comment by Vlix** [comment]
Done. From `password >= 3.1` we now use `crypton`.
