### ISSUE TITLE
add functionality for validating passwords

### ISSUE THREAD

**Issue by cdepillabout** [cdepillabout/password#9]
It would be nice if this package provided functionality for validating password requirements, such as password length, types of characters used (for instance, in systems that have requirements that a password must contain at least one symbol, one upper case character, one lower case character, etc).

I have a very, very basic TODO in the code for this type of thing:

https://github.com/cdepillabout/password/blob/1a37db09fa6f4ff91b65860f93073370bf4f38d1/password/src/Data/Password.hs#L254-L272

**Comment by HirotoShioi** [comment]
I'd like to work on this Issue, but before I do, do you think this type signature is appropriate?

```haskell
-- | Check if given 'Password' fills all the Policies,
-- return true if given password is valid
validatePassword' :: Password -> PasswordPolicy -> Bool

-- | Check if given 'Password' fills all the Policies, returns list of 
-- policies that failed.
validatePassword :: Password -> PasswordPolicy -> [FailedPolicies] 
```

I made a commit which has these functions implemented.
https://github.com/HirotoShioi/password/commit/f0d45bc2eb1ca58dff3ed2a977830dfa80c845ee

**Comment by cdepillabout** [comment]
@HirotoShioi Thanks for taking a look at this.

I think that API looks roughly good.  Feel free to open a PR.  We may have to go back and forth a few times working out a few rough edges.

**Comment by Vlix** [comment]
I feel this has been addressed with the `Data.Password.Validate` module.
